from vegans.models.unconditional.AAE import AAE
from vegans.models.unconditional.LSGAN import LSGAN
from vegans.models.unconditional.LRGAN import LRGAN
from vegans.models.unconditional.EBGAN import EBGAN
from vegans.models.unconditional.KLGAN import KLGAN
from vegans.models.unconditional.VAEGAN import VAEGAN
from vegans.models.unconditional.InfoGAN import InfoGAN
from vegans.models.unconditional.BicycleGAN import BicycleGAN
from vegans.models.unconditional.VanillaGAN import VanillaGAN
from vegans.models.unconditional.VanillaVAE import VanillaVAE
from vegans.models.unconditional.WassersteinGAN import WassersteinGAN
from vegans.models.unconditional.WassersteinGANGP import WassersteinGANGP

from vegans.models.conditional.ConditionalAAE import ConditionalAAE
from vegans.models.conditional.ConditionalLSGAN import ConditionalLSGAN
from vegans.models.conditional.ConditionalLRGAN import ConditionalLRGAN
from vegans.models.conditional.ConditionalEBGAN import ConditionalEBGAN
from vegans.models.conditional.ConditionalKLGAN import ConditionalKLGAN
from vegans.models.conditional.ConditionalVAEGAN import ConditionalVAEGAN
from vegans.models.conditional.ConditionalPix2Pix import ConditionalPix2Pix
from vegans.models.conditional.ConditionalCycleGAN import ConditionalCycleGAN
from vegans.models.conditional.ConditionalBicycleGAN import ConditionalBicycleGAN
from vegans.models.conditional.ConditionalVanillaGAN import ConditionalVanillaGAN
from vegans.models.conditional.ConditionalVanillaVAE import ConditionalVanillaVAE
from vegans.models.conditional.ConditionalWassersteinGAN import ConditionalWassersteinGAN
from vegans.models.conditional.ConditionalWassersteinGANGP import ConditionalWassersteinGANGP